### ISSUE TITLE
@turf/buffer 5.0.0 throws with "helpers.lengthToRadians is not a function" Error

### ISSUE THREAD

**Issue by trygve-lie** [Turfjs/turf#1081]
When using turf/buffer 5.0.0:

```js
const turfBuffer = require('@turf/buffer');

const collection =  {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
            "properties": {"prop0": "value0"}
        }
   ]
 };

const buffered = turfBuffer(collection, 500, {units: 'miles'});
```

it throws with:

```sh
/home/trygve/Dev/turf-dep/node_modules/@turf/buffer/main.js:118
    var distance = helpers.radiansToLength(helpers.lengthToRadians(radius, units), 'meters');
                                                   ^

TypeError: helpers.lengthToRadians is not a function
    at bufferFeature (/home/trygve/Dev/turf-dep/node_modules/@turf/buffer/main.js:118:52)
    at /home/trygve/Dev/turf-dep/node_modules/@turf/buffer/main.js:65:33
    at Object.featureEach (/home/trygve/Dev/turf-dep/node_modules/@turf/meta/main.js:314:13)
    at buffer (/home/trygve/Dev/turf-dep/node_modules/@turf/buffer/main.js:64:14)
    at Object.<anonymous> (/home/trygve/Dev/turf-dep/index.js:14:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by DenisCarriere** [comment]
Just published `v5.0` so this should be fixed now.

Try installing `v5.0.4` of `@turf/buffer`
