### ISSUE TITLE
PointGrid units is mandatory if other optional parameters set 

### ISSUE THREAD

**Issue by jpoynton** [Turfjs/turf#1177]
If you set a mask in PointGrid options then units attribute becomes mandatory as the kilometer defaulting not picked up as the options object is passed straight through to the distance calculation and then straight through to radiansToDistance helper. 
```
Error: Invalid unit
    at module.exports.radiansToDistance (/home/Jarrod/node_modules/@turf/helpers/index.js:289:37)
    at module.exports (/home/Jarrod/node_modules/@turf/distance/index.js:59:12)
    at module.exports (/home/Jarrod/node_modules/@turf/point-grid/index.js:36:33)
```
Code line to recreate
```
pointGrid(bbox, 1, {mask: mask});
```
Work around is pretty easy as just need to set the units in the options object.

**Comment by rowanwins** [comment]
Thanks @jpoynton , good pickup
