### ISSUE TITLE
Dissolve fails with some polygons

### ISSUE THREAD

**Issue by gdrouet** [Turfjs/turf#1208]
I have a polygons that cause an error when using `dissolve`.

For instance : http://bl.ocks.org/d/25604e12a46464195ac7708fd879b4fe
The stacktrace:
```
Error: features must be of the same type
    at booleanOverlap (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:18806:32)
    at C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:43566:18
    at Array.forEach (native)
    at Object.dissolve$1 [as dissolve] (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:43542:42)
    at featureCollections.features.forEach.e (C:\Users\gdrouet\Documents\nomotech\index.js:20:40)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\gdrouet\Documents\nomotech\index.js:9:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```
All features are polygons.

**Comment by DenisCarriere** [comment]
🤔 ... sounds like this could be a bug. The `@turf/dissolve` module is kinda a mess, what if you used the `@turf/union` module instead as a temporary fix?

**Comment by gdrouet** [comment]
This is what I've already done done and works well :)
Thanks.

**Comment by 015988** [comment]
Union doesn't consider properties, so I would have to create separate arrays for each kind of feature, then union them, then combine the results?
