### ISSUE TITLE
Union of a polygon and its simplified version fails

### ISSUE THREAD

**Issue by gdrouet** [Turfjs/turf#1209]
I have a set of polygons that I simplify.
Then I compute the union of this simplification with its original version.
I have some case when the following error occurs:

```
{ Error
    at TopologyException.RuntimeException [as constructor] (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:24925:19)
    at new TopologyException (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:30875:25)
    at DirectedEdgeStar.propagateSideLabels (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:35610:43)
    at DirectedEdgeStar.computeLabelling (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:35711:8)
    at DirectedEdgeStar.computeLabelling (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:35977:47)
    at OverlayOp.computeLabelling (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:40900:23)
    at OverlayOp.computeOverlay (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:40838:10)
    at OverlayOp.getResultGeometry (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:40812:10)
    at Function.OverlayOp.overlayOp (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:40935:20)
    at SnapIfNeededOverlayOp.getResultGeometry (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:39762:24)
  name: 'TopologyException',
  message: 'side location conflict',
  stack: 'Error\n    at TopologyException.RuntimeException [as constructor] (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:24925:19)\n    at new TopologyException (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:3
0875:25)\n    at DirectedEdgeStar.propagateSideLabels (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:35610:43)\n    at DirectedEdgeStar.computeLabelling (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:35711:8)\n
   at DirectedEdgeStar.computeLabelling (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:35977:47)\n    at OverlayOp.computeLabelling (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:40900:23)\n    at OverlayOp.comp
uteOverlay (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:40838:10)\n    at OverlayOp.getResultGeometry (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:40812:10)\n    at Function.OverlayOp.overlayOp (C:\\Users\\g
drouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:40935:20)\n    at SnapIfNeededOverlayOp.getResultGeometry (C:\\Users\\gdrouet\\Documents\\nomotech\\node_modules\\@turf\\turf\\turf.js:39762:24)',
  pt: Coordinate { x: -1.2767639133054933, y: 48.63582536868326, z: undefined } }
```

Ex 1:
- original: http://bl.ocks.org/d/01d17aa8a50abdc7d57ef59bc9298d52
- simplified: http://bl.ocks.org/d/2c25a0e73b0a7c4b52e33f5465dfa0dd

Ex 2:
- original: http://bl.ocks.org/d/753197f993b85a1c103d2d5bbf082422
- simplified: http://bl.ocks.org/d/74df8ec410dde61617466bffd43d1e76

Ex 3:
- original: http://bl.ocks.org/d/23464dafcf12d9135c069f84197576dc
- simplified: http://bl.ocks.org/d/5e2c7d6e97e4b7b4fc40bd75261fb26b

Ex 4:
- original: http://bl.ocks.org/d/ad7fe5a760b245ebc9242248534ecced
- simplified: http://bl.ocks.org/d/aaeb9511720658c4228469ca728eb394

Ex 5:
- original: http://bl.ocks.org/d/64b84c664e203d3b5a3e9d4ddb1b442b
- simplified: http://bl.ocks.org/d/9f638d35bfe4da05d09bb03c60036252

You can see that simplified polygons are kinked, maybe this is linked.

**Comment by gdrouet** [comment]
I confirm that if I unkink the simplified polygons and then compute the union of all the resulting polygons with the original version, I obtain a valid workaround.

**Comment by rowanwins** [comment]
Thanks for the detailed report @gdrouet , we aware that our union function doesn't handle self intersecting polygons very well, it currently relies on the jsts library, but we write close to replacing this dependency with something that does, so stay tuned!

**Comment by tmcw** [comment]
Closing; #88 is the tracking issue for JSTS.
