### ISSUE TITLE
Missing index.js file in @turf/nearest-point-on-line

### ISSUE THREAD

**Issue by fnogatz** [Turfjs/turf#1280]
Hi!

When installing `@turf/nearest-point-on-line` with v6.0.0 it is appearently missing the `index.js` file on npm:

```sh
$ npm install @turf/nearest-point-on-line
+ @turf/nearest-point-on-line@6.0.0
added 19 packages in 4.681s
$ node
> var n = require('@turf/nearest-point-on-line')
Error: Cannot find module '@turf/nearest-point-on-line'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
$ ll node_modules/@turf/nearest-point-on-line 
total 52K
-rw-rw-r-- 1 fnogatz fnogatz 4,2K Feb 21 19:35 index.ts
-rw-rw-r-- 1 fnogatz fnogatz 1,1K Feb  3 17:06 LICENSE
-rw-rw-r-- 1 fnogatz fnogatz 2,0K Feb 21 20:58 package.json
-rw-rw-r-- 1 fnogatz fnogatz 2,9K Feb  3 17:06 README.md
```

**Comment by DenisCarriere** [comment]
Thanks @fnogatz for the quick response, I republished `@turf/nearest-point-on-line` and the `index.js` is now included.
