### ISSUE TITLE
boolean-overlap v6 missing dependency

### ISSUE THREAD

**Issue by eczajk1** [Turfjs/turf#1294]
Just installed `boolean-overlap` and got v6. But when I run my app I get a missing dependency error:

```
Error: Cannot find module 'deep-equal'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/redacted/node_modules/@turf/boolean-overlap/node_modules/@turf/line-overlap/index.js:10:13)
```

Install:

```
npm install @turf/boolean-overlap --save
@turf/boolean-overlap@6.0.0 node_modules/@turf/boolean-overlap
├── @turf/invariant@6.0.1
├── @turf/meta@6.0.1
├── geojson-equality@0.1.6 (deep-equal@1.0.1)
├── @turf/line-intersect@6.0.0 (@turf/line-segment@6.0.0, geojson-rbush@3.1.1)
└── @turf/line-overlap@6.0.0 (@turf/line-segment@6.0.0, @turf/boolean-point-on-line@6.0.0, geojson-rbush@3.1.1, @turf/nearest-point-on-line@6.0.1)
```

Thanks!

**Comment by DenisCarriere** [comment]
@eczajk1 thanks for catching this error, I've added `deep-equal` as a dependency for `@turf/line-overlap`.

An npm patch release has been published `v6.0.1`

Don't hesitate to re-open if it still doesn't work.
