### ISSUE TITLE
Character.isDigit is not a function  

### ISSUE THREAD

**Issue by bcolston** [Turfjs/turf#1354]
I am merging multiple polygons by using turf.union and will occasionally get an exception message.
Exception Message:
"TypeError: Character.isDigit is not a function
at Function.parse (..\node_modules\@turf\turf\turf.js:23791:19)
at Function.valueOf (..\node_modules\@turf\turf\turf.js:23762:15)
at Function.orientationIndex (..\node_modules\@turf\turf\turf.js:23880:16)
at Function.orientationIndex (..\node_modules\@turf\turf\turf.js:25702:25)
at RobustLineIntersector.computeIntersect (..\node_modules\@turf\turf\turf.js:25338:28)
at RobustLineIntersector.computeIntersection (..\node_modules\@turf\turf\turf.js:25044:23)
at RobustLineIntersector.computeIntersection (..\node_modules\@turf\turf\turf.js:25200:70)
at SegmentIntersector.addIntersections (..\node_modules\@turf\turf\turf.js:39977:12)
at MonotoneChainEdge.computeIntersectsForChain (..\node_modules\@turf\turf\turf.js:36433:10)
at MonotoneChainEdge.computeIntersectsForChain (..\node_modules\@turf\turf\turf.js:36420:10)"

I searched for Character.isDigit and did not find it in the turf source code.

I resolved the issue by adding the following line to turf.js on line 23233 just below the Character.isWhitespace and Character.toUpperCase implementation:
Character.isDigit = function isDigit(c) { return (c >= '0' && c <= '9') };

Version: 5.1.6

**Comment by rowanwins** [comment]
Hi @bcolston 

This likely comes from JSTS (on which turf/union depends) which we are hoping to remove in v6. Thanks for reporting and including a fix.

**Comment by rowanwins** [comment]
Resolved since v6.2.0
