### ISSUE TITLE
browserify dont work with @turf/intersect

### ISSUE THREAD

**Issue by IMMSPgisgroup** [Turfjs/turf#1372]
We do all as in [http://turfjs.org/getting-started](url). But
```
e:\Projects\npm>npm install @turf/intersect
npm WARN saveError ENOENT: no such file or directory, open 'e:\Projects\npm\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'e:\Projects\npm\package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.

+ @turf/intersect@6.1.1
added 6 packages in 5.716s

e:\Projects\npm>browserify main.js -s turf > outTurf.js
Error: Cannot find module './src/index' from 'e:\Projects\npm\node_modules\martinez-polygon-clipping\dist'
    at C:\Users\ScienceKitten\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\ScienceKitten\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\ScienceKitten\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\ScienceKitten\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```
main.js are
```
module.exports = {
    intersect: require('@turf/intersect')
};
```
What we do wrong?
_________________________________________________________________________________________________________

With respect, IMMSPgisgroup

**Comment by rowanwins** [comment]
perhaps try and run `npm init` first - that'll setup your project, you'll just need to give it a project name and a couple of other basic parameters

**Comment by rowanwins** [comment]
Actually sorry - looks like the martinez (on which the new turf/intersect module relies) build process is a bit broken at the moment

**Comment by DenisCarriere** [comment]
@IMMSPgisgroup Can you try it again, I refactored & re-published `@turf/intersect`

**Comment by DenisCarriere** [comment]
If it doesn't work, it might be because of `martinez` 🤔 We might need to define an exact version if that's the case.
