### ISSUE TITLE
Error after building @turf/intersect 6.1.2 with webpack

### ISSUE THREAD

**Issue by PizzaBrandon** [Turfjs/turf#1400]
After building @turf/intersect with webpack 3 (using default settings provided by `create-react-app`), intersect does not run due to a problem with turf's import of `martinez-polygon-clipping`:

```
TypeError: martinez.intersection is not a function
    at intersect (http://localhost:3000/static/js/bundle.js:1538:37)
    at Object../src/App.js (http://localhost:3000/static/js/bundle.js:39523:72)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object../src/index.js (http://localhost:3000/static/js/bundle.js:39638:63)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object.0 (http://localhost:3000/static/js/bundle.js:39664:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at ./node_modules/@turf/helpers/index.js.Object.defineProperty.value (http://localhost:3000/static/js/bundle.js:725:37)
    at http://localhost:3000/static/js/bundle.js:728:10
```

I built a minimal demonstration for this bug: https://github.com/PizzaBrandon/bug-reports/tree/master/turf-intersect-6-1-2

I am pulling down the turf repo now to try to address this, but I wanted to get visibility around this bug now.

Other packages may also be affected by this and I'll update the linked demo as they are discovered.

**Comment by PizzaBrandon** [comment]
PR filed #1401
