### ISSUE TITLE
 Error: Unable to resolve module `./lib/spline` from /node_modules/@turf/bezier-spline/index.js

### ISSUE THREAD

**Issue by zinoviev** [Turfjs/turf#1402]
Hi there. I just try to import this module and seems file 'spline.js' is rly missing from npm package. Where are only typescript typings inside of 'lib' folder. The version is ^6.0.2

error: bundling failed: Error: Unable to resolve module `./lib/spline` from `/Users/zigi/Sources/raccooninst_rn/node_modules/@turf/bezier-spline/index.js`: The module `./lib/spline` could not be found from `/Users/zigi/Sources/raccooninst_rn/node_modules/@turf/bezier-spline/index.js`. Indeed, none of these files exist:

  * `/Users/zigi/Sources/raccooninst_rn/node_modules/@turf/bezier-spline/lib/spline(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/zigi/Sources/raccooninst_rn/node_modules/@turf/bezier-spline/lib/spline/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/zigi/Sources/raccooninst_rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473

**Comment by rnauthon** [comment]
Hi, same issue, the file "spline.js" is missing:

./node_modules/@turf/bezier-spline/index.js
Module not found: Can't resolve './lib/spline' in 'D:\Projets\results-react-2\node_modules\@turf\bezier-spline'

**Comment by rowanwins** [comment]
Thanks @zinoviev & @rnauthon 

Taking a look I think it's because of a conflict between the `.gitignore` and the `.npmignore`. I seem to be having troubles publishing at the moment so I haven't quite been able to resolve but stayed tuned.

Thanks,
Rowan

**Comment by rowanwins** [comment]
Hi @zinoviev & @rnauthon 

This is resolved with v6.0.3 which is now published.

Cheers

**Comment by rnauthon** [comment]
Thanks @rowanwins !
