### ISSUE TITLE
Unable to calculate distance in degrees for two points

### ISSUE THREAD

**Issue by frewsxcv** [Turfjs/turf#1449]
```javascript
const turf = require('turf');

const nyc = turf.point([-74.006, 40.7128])
const moscow = turf.point([37.6173, 55.7558])

const distance = turf.distance(nyc, moscow, {units: 'degrees'});
```

```
Error: Invalid unit
    at module.exports.radiansToDistance (/private/tmp/dis-js/node_modules/turf-helpers/index.js:286:15)
    at Object.module.exports [as distance] (/private/tmp/dis-js/node_modules/turf-distance/index.js:59:12)
```

Am I doing something wrong here? This seems to match what the `distance` docs recommend: http://turfjs.org/docs#distance

**Comment by rowanwins** [comment]
Hi @frewsxcv 

Hmmm do you know which version of `turf` you've installed?

Cheers
Rowan

**Comment by rowanwins** [comment]
Ah yes that's it :)
