### ISSUE TITLE
turf.buffer not accepting valid Points

### ISSUE THREAD

**Issue by zedman** [Turfjs/turf#1522]
Im getting some weird behaviour with Buffer. The function succeeds with one Point but fails if i substitute it for a few others. Example:

This works...
```
let p = turf.point([-90.54863, 14.616599]);
let buffered = turf.buffer(p, 25, { units: "meters" });
```

This does not...
```
let p = turf.point([37.37, -122.14]);
let buffered = turf.buffer(p, 25, { units: "meters" });
```
Funnily, the first example that works isn't using a valid geolocation (as lat is less than -90), but it's the example [value seen here in the documentation](https://github.com/Turfjs/turf/tree/master/packages/turf-buffer).

The error returned is the following (where Factory.js:87:23 is referencing turf.buffer in the code above)

```
TypeError: Cannot read property 'getEdge' of null
    at RightmostEdgeFinder.findRightmostEdgeAtVertex (/Users/me/dev/project/node_modules/@turf/turf/turf.js:30798:25)
    at RightmostEdgeFinder.findEdge (/Users/me/dev/project/node_modules/@turf/turf/turf.js:30858:10)
    at BufferSubgraph.create (/Users/me/dev/project/node_modules/@turf/turf/turf.js:30960:16)
    at BufferBuilder.createSubgraphs (/Users/me/dev/project/node_modules/@turf/turf/turf.js:36823:16)
    at BufferBuilder.buffer (/Users/me/dev/project/node_modules/@turf/turf/turf.js:36855:27)
    at BufferOp.bufferOriginalPrecision (/Users/me/dev/project/node_modules/@turf/turf/turf.js:37514:39)
    at BufferOp.computeGeometry (/Users/me/dev/project/node_modules/@turf/turf/turf.js:37503:8)
    at BufferOp.getResultGeometry (/Users/me/dev/project/node_modules/@turf/turf/turf.js:37523:8)
    at Function.bufferOp (/Users/me/dev/project/node_modules/@turf/turf/turf.js:37540:24)
    at bufferFeature (/Users/me/dev/project/node_modules/@turf/turf/turf.js:43211:29)
    at Object.buffer$1 [as buffer] (/Users/me/dev/project/node_modules/@turf/turf/turf.js:43166:12)
    at _class.getPoints (/Users/me/dev/project/components/Factory.js:87:23)
```

**Comment by zedman** [comment]
Just wanted to resolve my own issue, as this might trip others up (and waste 3 hours of your weekend as I did).

Geolocations need to be specified the opposite way to what you would consider 'normal'. Rather than [lat,long] you need to pass [long,lat]. This is because typically coordinates are specified as [x,y], which maps to [long,lat].
