### ISSUE TITLE
TypeError: turfBBox is not a function

### ISSUE THREAD

**Issue by arunasank** [Turfjs/turf#1545]
I am trying to use the v7.0.0-alpha.1, but I see this error, when a call to `turf.lineSplit` is made

```
0 tiles processed in 1s/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:12203
            else if (geojson.type === 'Feature') bbox = turfBBox(geojson);
                                                        ^

TypeError: turfBBox is not a function
    at rbush.tree.toBBox (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:12203:57)
    at rbush.tree.search (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:12119:69)
    at splitLineWithPoint (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:15054:27)
    at /Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:14999:27
    at /Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:1326:21
    at geomEach (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:1214:25)
    at flattenEach (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:1318:9)
    at splitLineWithPoints (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:14992:9)
    at Object.lineSplit (/Users/arunasank/berkeley/old-pipeline/node_modules/turf/dist/turf.js:14976:20)
    at givePolygons.features.forEach (/Users/arunasank/berkeley/old-pipeline/map.js:47:39)
```

**Comment by rlueder** [comment]
related to https://github.com/Turfjs/turf/issues/1478

**Comment by mfedderly** [comment]
We aren't really supporting that v7.0.0 series of releases. I'm going to close this but feel free to reopen if this comes up in the 6.x or the future 7.x branches.
