### ISSUE TITLE
specifying options for turf.simplify in TypeScript

### ISSUE THREAD

**Issue by MartinB-nx** [Turfjs/turf#2204]
Turf version: 6.5.0

Hello,

I am trying to use the simplify function in my code written in TypeScript. There seems to be no functioning way to specify the options though. Trying to replicate the [example from the documentation](https://turfjs.org/docs/#simplify) bascially 1:1:

```
import simplify from '@turf/simplify'
import { polygon } from '@turf/helpers'

const geojson = polygon([
  [
    [-70.603637, -33.399918],
    [-70.614624, -33.395332],
    [-70.639343, -33.392466],
    [-70.659942, -33.394759],
    [-70.683975, -33.404504],
    [-70.697021, -33.419406],
    [-70.701141, -33.434306],
    [-70.700454, -33.446339],
    [-70.694274, -33.458369],
    [-70.682601, -33.465816],
    [-70.668869, -33.472117],
    [-70.646209, -33.473835],
    [-70.624923, -33.472117],
    [-70.609817, -33.468107],
    [-70.595397, -33.458369],
    [-70.587158, -33.442901],
    [-70.587158, -33.426283],
    [-70.590591, -33.414248],
    [-70.594711, -33.406224],
    [-70.603637, -33.399918]
  ]
])
const options = { tolerance: 0.01, highQuality: false }
simplify(geojson, options)
```

This gives me a compile time error: 

> $ tsc
src/test.ts:29:20 - error TS2554: Expected 3 arguments, but got 2.
29 const simplified = simplify(geojson, options)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@types/turf/index.d.ts:467:126
    467     simplify(feature: GeoJSON.Feature<any> | GeoJSON.FeatureCollection<any> | GeoJSON.GeometryCollection, tolerance: number, highQuality: boolean): GeoJSON.Feature<any> | GeoJSON.FeatureCollection<any> | GeoJSON.GeometryCollection;                                                                                                                                     ~~~~~~~~~~~~~~~~~~~~
    An argument for 'highQuality' was not provided.
Found 1 error.
error Command failed with exit code 2.

Seeing this message, I also tried calling simplify without an options object but by specifying the tolerance and highQuality as second and third parameters:

`const simplified2 = simplify(geojson, 0.01, false)`

This compiles fine but throws an Error at runtime:

>node dist/test.js
.../node_modules/@turf/simplify/dist/js/index.js:164
  if (!helpers.isObject(options)) throw new Error("options is invalid");
Error: options is invalid
    at Object.simplify$1 [as default] (.../node_modules/@turf/simplify/dist/js/index.js:164:41)
    at Object.<anonymous> (.../dist/test.js:34:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

Am I missing a third, actually correct way to use in this situation?

**Comment by tunnelpuzzle** [comment]
The package '@types/turf' is deprecated https://www.npmjs.com/package/@types/turf. I think the using the types from '@turf/turf'  will fix the typescript error.

**Comment by JamesLMilner** [comment]
@MartinB-nx can you confirm you still have this issue after uninstalling `@types/turf` and using the `@turf/simplify` types directly?

Looks like this should be fine: https://github.com/Turfjs/turf/blob/84110709afda447a686ccdf55724af6ca755c1f8/packages/turf-simplify/index.d.ts#L10

If there's no follow up by the end of the week I will assume this is a resolved problem.

**Comment by MartinB-nx** [comment]
That did the trick. Thanks a lot for your help! And sorry for not realizing the deprecation message.
