### ISSUE TITLE
Turf.js function is hit or miss when I load my webpage

### ISSUE THREAD

**Issue by yahyadeen** [Turfjs/turf#2252]
Hi, I am using version 5.1.6 of turf. I am trying to loop through a geojson of bikeshare stations in toronto to determine which jurisdiction each bikeshare station falls in. The problem I am running into is that my webpage is hit or miss when I refresh the page. Here is my code:

```js
map.on('load', function () {

    addLayers_jurisdictions()

    $.ajax({
        method: "GET",
        url: "https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information",
        dataType: 'json'
    })
        .done(function (data) {
            create_geojson(data);
            createNumStationsChart(num_bikestations_etob, num_bikestations_ny, num_bikestations_scarb, num_bikestations_tor)
        })

        .fail(function () {
            alert("OH NO! FAILED!");
        });

    function create_geojson (data) {

        for (i = 0; i < data.data.stations.length; i++) {
            var point = turf.point([data.data.stations[i].lon, data.data.stations[i].lat])
            var within_scarb = turf.booleanPointInPolygon(point, scarb_poly)
            var within_etob = turf.booleanPointInPolygon(point, etob_poly)
            var within_tor = turf.booleanPointInPolygon(point, tor_poly)
            var within_ny = turf.booleanPointInPolygon(point, ny_poly)

            if (within_scarb == true) {
                num_bikestations_scarb++;
                bikeshare_station_geojson.features.push({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [data.data.stations[i].lon, data.data.stations[i].lat]
                    },
                    "properties": {
                        "name": data.data.stations[i].name,
                        "capacity": data.data.stations[i].capacity,
                        "jurisdiction": "Scarborough"
                    }
                });
            } else if (within_etob == true) {
                num_bikestations_etob++;
                bikeshare_station_geojson.features.push({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [data.data.stations[i].lon, data.data.stations[i].lat]
                    },
                    "properties": {
                        "name": data.data.stations[i].name,
                        "capacity": data.data.stations[i].capacity,
                        "jurisdiction": "Etobicoke"
                    }
                });
            } else if (within_ny == true) {
                num_bikestations_ny++;
                bikeshare_station_geojson.features.push({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [data.data.stations[i].lon, data.data.stations[i].lat]
                    },
                    "properties": {
                        "name": data.data.stations[i].name,
                        "capacity": data.data.stations[i].capacity,
                        "jurisdiction": "North York"
                    }
                });
            } else {
                num_bikestations_tor++;
                bikeshare_station_geojson.features.push({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [data.data.stations[i].lon, data.data.stations[i].lat]
                    },
                    "properties": {
                        "name": data.data.stations[i].name,
                        "capacity": data.data.stations[i].capacity,
                        "jurisdiction": "Toronto & East York"
                    }
                });
            }
        }

    };

    setTimeout(addLayers_cityWards, 1200)
    setTimeout(addLayers_bikeways, 1400);
    setTimeout(addLayers, 1600);

});
```

The error i get when i open the console is this:
```
Uncaught Error: coordinates must only contain numbers
    at Y (turf.min.js:1:9901)
    at U (turf.min.js:1:9742)
    at Object.Pt (turf.min.js:1:20475)
    at create_geojson (torontocyclingnetwork:567:32)
    at Object.<anonymous> (torontocyclingnetwork:555:6)
    at c (jquery-3.5.1.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:2:29039)
    at l (jquery-3.5.1.min.js:2:79800)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2:82254)
```

What's confusing is that this doesn't happen all the time. Any ideas on what may be causing this?

**Comment by JamesLMilner** [comment]
I don't think this is an actual Turf.js issue, I think you have some issues with asynchronous calls and the use of setTimeout, this is also much more likely as your issue only occurs part of the time. I would suggest we close this unless you have any evidence that this is a Turf.js issue directly.

**Comment by stebogit** [comment]
I agree with @JamesLMilner, @yahyadeen I suggest you isolate the issue identifying the actual data the Turf function(s) receive and evaluate the output. In this case I bet in some cases your `data.data.stations` variable does not contain what you expect.
If you find any unexpected behavior please open a new issue here providing a specific example (best if in a jsfiddle or similar environments) that highlights the actual Turf issue.
