### ISSUE TITLE
Bug with turf.random() in 3.0.14 

### ISSUE THREAD

**Issue by lleaky** [Turfjs/turf#2353]
my turf  version  is 3.0.14. I want to use turf.random() to generate some random points in some bbox. My source code is :

```javascript
let points = turf.random("points",25, {bbox:bbox})
```

However, I get error as following:

```javascript
Uncaught ReferenceError: i is not defined
    at module.exports.point (index.js:14:10)
    at module.exports [as random] (index.js:40:23)
    at Object.init (HelloWorld.vue:56:23)
    at HelloWorld.vue:61:22
    at runtime-core.esm-bundler.js:2710:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2684:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:341:32)
    at render2 (runtime-core.esm-bundler.js:6230:9)
```

I go to turf source code ,it seems that  the error comes from the following,that  i is not defined

```javascript
module.exports.point = function(count, bbox) {
    var features = [];
    for (i = 0; i < count; i++) {
        features.push(feature(bbox ? point(position(bbox)) : point()));
    }
    return collection(features);
};
```

**Comment by tmcw** [comment]
The solution to this is updating from turf 3.0.14 to the `@turf/turf` module. 3.0.14 was published 6 years ago and has this bug, which was fixed in 2015 in this commit: https://github.com/tmcw/geojson-random/commit/a81deb6bf7297dad9ca4297b2f8641d2f9e557f2 - using a current release of turf will resolve this issue.
