### ISSUE TITLE
Exception occurs when trying to calculate area of Polygon using Mapbox GL

### ISSUE THREAD

**Issue by djpirra** [Turfjs/turf#2428]
I am currently trying to calculate the area of a selected feature from the buildings layer in Mapbox GL.

Once I have clicked the feature I get the feature but when I try to calculate the area using:

`console.log(turf.area(features[0]));`

I am getting this error:
```shell
caught ReferenceError: i is not defined
    at ringArea (index.js:61:14)
    at polygonArea (index.js:32:26)
    at geometry (index.js:10:20)
    at Object.area (index.js:58:16)
    at Map.<anonymous> (Map.jsx?t=1682437990307:75:26)
    at Map.fire (evented.js:130:26)
    at _r.click (map_event.js:54:19)
    at $r.handleEvent (handler_manager.js:402:58)
```

This is the structure of features[0]:

```json
{
    "type": "Feature",
    "state": {},
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -9.079756289720535,
                    38.98317406638486
                ],
                [
                    -9.079427719116211,
                    38.98299892923288
                ],
                [
                    -9.079371392726898,
                    38.983063563232264
                ],
                [
                    -9.079241305589676,
                    38.98299475929542
                ],
                [
                    -9.079469293355942,
                    38.98273413771611
                ],
                [
                    -9.079595357179642,
                    38.98280085693179
                ],
                [
                    -9.079526960849762,
                    38.9828780009465
                ],
                [
                    -9.079860895872116,
                    38.98305522336469
                ],
                [
                    -9.079756289720535,
                    38.98317406638486
                ]
            ]
        ]
    },
    "properties": {
        "underground": "false",
        "extrude": "true",
        "height": 3,
        "min_height": 0,
        "iso_3166_1": "PT",
        "type": "building"
    },
    "id": 364673432,
    "layer": {
        "id": "add-3d-buildings",
        "type": "fill-extrusion",
        "source": "composite",
        "source-layer": "building",
        "minzoom": 14,
        "filter": [
            "==",
            "extrude",
            "true"
        ],
        "paint": {
            "fill-extrusion-color": {
                "r": 0.6666666666666666,
                "g": 0.6666666666666666,
                "b": 0.6666666666666666,
                "a": 1
            },
            "fill-extrusion-height": 3,
            "fill-extrusion-base": 0,
            "fill-extrusion-opacity": 0.7
        },
        "layout": {}
    },
    "source": "composite",
    "sourceLayer": "building"
}
```

Thank you

**Comment by JamesLMilner** [comment]
Hi @djpirra - I can't replicate this on CodeSandbox: https://codesandbox.io/s/turf-issue-2428-k5ciio?file=/src/index.ts

What version of turf are you using?

**Comment by djpirra** [comment]
> Hi @djpirra - I can't replicate this on CodeSandbox: https://codesandbox.io/s/turf-issue-2428-k5ciio?file=/src/index.ts
> 
> 
> 
> What version of turf are you using? 

Latest version just installed today.

**Comment by JamesLMilner** [comment]
> > Hi @djpirra - I can't replicate this on CodeSandbox: https://codesandbox.io/s/turf-issue-2428-k5ciio?file=/src/index.ts
> > What version of turf are you using?
> 
> Latest version just installed today.
> 
> Also the link you shared seems to refer to a Point example and not an area using the Polygon structure I submitted. Was it tested like this?

The CodeSandbox hadn't saved for some reason, please try again. 

The result comes out as 1024.420

**Comment by smallsaucepan** [comment]
No feedback provided for some time. Please reopen though if need be.
