### ISSUE TITLE
ESM and ViteJS 5 : Building error with density-clustering

### ISSUE THREAD

**Issue by erwanlpfr** [Turfjs/turf#2541]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Hello,

Using : `"@turf/turf": "7.0.0-alpha.2"` and the last ViteJS version (5).
I get a building error with `density-clustering` which is a direct dependancy of turf.

```bash
vite v5.0.0 building for production...
✓ 13211 modules transformed.
[commonjs--resolver] Expected '(', got 'string literal (object, 'object')'
file: /Users/aa/Documents/web/node_modules/density-clustering/lib/index.js:211:3
209: };
210: 
211: if (typeof module !== 'undefined' && module.exports) {
        ^
212:   module.exports = KMEANS;
213: }
error during build:
RollupError: Expected '(', got 'string literal (object, 'object')'
    at error (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at nodeConverters (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/parseAst.js:2090:9)
    at convertNode (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/parseAst.js:975:12)
    at convertProgram (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/parseAst.js:966:48)
    at parseAstAsync (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/parseAst.js:2156:20)
    at async Module.tryParseAsync (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/node-entry.js:13490:21)
    at async Module.setSource (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/node-entry.js:13071:35)
    at async ModuleLoader.addModuleSource (file:///Users/aa/Documents/web/node_modules/rollup/dist/es/shared/node-entry.js:17713:13)
```
It came, probably, from the ESM option in `package.json` and the new building settings with ViteJS.
Let me know if there is a possible fork to do or whatever!

Thank you !

**Comment by sideral** [comment]
I could solve this error by forcing Vite to use the latest version of Rollup (related to [this issue](https://github.com/rollup/rollup/issues/5258)), in my package.json I added:

``` 
"overrides": {
  "vite": {
    "rollup": "^4.6.1"
  }
}
```

**Comment by smallsaucepan** [comment]
Good find @sideral. Do you want to try that workaround @erwanlpfr?

**Comment by smallsaucepan** [comment]
@erwanlpfr I'll close this issue as it sounds like it's a problem vite needs to address and there's a workaround.

Worth noting 7.0.0-alpha.3 is on the way which should include some more consistent type exporting. Don't think it would address this issue, though if you're already in alpha territory would be interested to hear your experiences when it drops.
