### ISSUE TITLE
turf-buffer: TypeError: Cannot read property 'getEdge' of null on 3.0.3

### ISSUE THREAD

**Issue by andreabadesso** [Turfjs/turf#386]
How to reproduce it:
```
let feature = {
    type: 'Feature',
    geometry: {
        type: 'Point',
        coordinates: ['-43.356161', '-22.948926']
    }
};

turf.buffer(feature, 500, 'kilometers');
```

> Stacktrace:

```
TypeError: Cannot read property 'getEdge' of null
    at zi.e.findRightmostEdgeAtVertex (node_modules/jsts/dist/jsts.min.js:15:14102)
    at zi.e.findEdge (/node_modules/jsts/dist/jsts.min.js:15:15465)
    at ki.e.create (/node_modules/jsts/dist/jsts.min.js:15:16668)
    at Qi.e.createSubgraphs (node_modules/jsts/dist/jsts.min.js:16:4556)
    at Qi.e.buffer (node_modules/jsts/dist/jsts.min.js:16:5210)
    at sr.e.bufferOriginalPrecision (node_modules/jsts/dist/jsts.min.js:16:14741)
    at sr.e.computeGeometry (node_modules/jsts/dist/jsts.min.js:16:14380)
    at sr.e.getResultGeometry (node_modules/jsts/dist/jsts.min.js:16:14904)
    at Function.sr.bufferOp (node_modules/jsts/dist/jsts.min.js:16:15168)
    at Lt.e.buffer (node_modules/jsts/dist/jsts.min.js:19:28373)
```

**Comment by andreabadesso** [comment]
Investigating the issue, it starts breaking on *jsts* version 1.0.0-beta2. Works fine on 0.17.0

**Comment by andreabadesso** [comment]
Found the issue, coordinates can't be strings, this is expected since *positions* should be represented by an array of *numbers*, not strings.

Closing the issue.

Should turf treat this?

**Comment by andreabadesso** [comment]
Opened a pull request for geojson-normalize that is being used internally on turf.js:

https://github.com/mapbox/geojson-normalize/pull/1

It should fix the issue automatically, preventing the refactor of many webapps.

**Comment by morganherlocker** [comment]
> Should turf treat this?

No, turf will always assume that the data it is passed is valid GeoJSON. Behavior will be undefined if you pass anything other than valid simple feature compliant GeoJSON.

**Comment by crabmusket** [comment]
I was having the same issue, then I realised that GeoJSON uses lon,lat coordinates but I had passed lat,lon. 😅
