### ISSUE TITLE
Error loading turf

### ISSUE THREAD

**Issue by bloigge** [Turfjs/turf#523]
When I try to require turf in a new project (tested on linux and windows) I am always getting this error:

`module.js:338
    throw err;
          ^
Error: Cannot find module 'turf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<somePath>/kmlCleanUp/kmlcleanup.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
`

Installed it using npm install @turf/turf --save in a fresh npm project

**Comment by tmcw** [comment]
Dos your code in kmlcleanup.js say `require('turf')` or `require('@turf/turf')`? It should say the latter.

**Comment by bloigge** [comment]
shame on me - thank you! require('@turf/turf') it is!
