### ISSUE TITLE
turf-intersection found non-noded intersection between LINESTRING

### ISSUE THREAD

**Issue by scbytron** [Turfjs/turf#548]
Hi

Getting an odd error when processing multiple features through turf-intersection in a node application:

```
{ Error
    at sn.l (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:6:424)
    at new sn (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:6:17532)
    at un.e.checkValid (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:12:7761)
    at ln.e.checkValid (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:12:8294)
    at Function.ln.checkValid (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:12:8556)
    at ii.e.computeOverlay (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:4)
    at ii.e.getResultGeometry (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:13:31486)
    at Function.ii.overlayOp (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:2252)
    at si.e.getResultGeometry (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:5597)
    at Function.si.overlayOp (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:5935)
  pt: g { x: -105.0075133882537, y: 51.04815510047183, z: undefined },
  name: 'TopologyException',
  message: 'found non-noded intersection between LINESTRING ( -107.14 53.29, -104.8 50.83 ) and LINESTRING ( -124.81353339513886 50.224322159762124, -10.00 55.00 ) [ (-105.0075133882537, 51.04815510047183, undefined) ]',
  stack: 'Error\n    at sn.l (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:6:424)\n    at new sn (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:6:17532)\n    at un.e.checkValid (.node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:12:7761)\n    at ln.e.checkValid (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:12:8294)\n    at Function.ln.checkValid (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:12:8556)\n    at ii.e.computeOverlay (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:4)\n    at ii.e.getResultGeometry (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:13:31486)\n    at Function.ii.overlayOp (.node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:2252)\n    at si.e.getResultGeometry (./node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:5597)\n    at Function.si.overlayOp (/Users/simon/Sites/skybookv2/node/web125-bufrserver/node_modules/jsts/dist/jsts.min.js:14:5935)' }
{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-144.59,39.32],[-141.9,42.45],[-137.93,45.35],[-131.79,47.55],[-124.43,47.96],[-124.95,51.03],[-129.36,51.87],[-135.16,50.57],[-134.9,52.65],[-127.46,55.67],[-120.28,56.4],[-113.54,55.67],[-109.91,54.74],[-107.14,53.29],[-104.8,50.83],[-102.73,51.74],[-106.01,55.36],[-115.35,58.03],[-128.5,58.92],[-136.2,56.71],[-139.92,52.9],[-144.41,54.17],[-167.85,52.9],[-177.8,50.5],[179.7,48.64],[179.96,47.01],[-171.66,49.11],[-166.81,49.57],[-164.82,49.17],[-163.01,49.04],[-159.81,49.37],[-157.3,49.91],[-154.79,49.11],[-150.99,46.87],[-146.75,40.64],[-144.59,39.32]]}}
```
The issue only seems to occur when the feature crosses the date line.

Version of @turf/turf is 3.7.4

**Comment by tmcw** [comment]
Hi,

Thanks for the report, I'm going to merge this with #463 which is an earlier report of the same problem.

- Tom
