### ISSUE TITLE
Error Installing @turf/square-grid

### ISSUE THREAD

**Issue by rsancheza09** [Turfjs/turf#913]
Hello Guys,

I am some this issue installing the package `@turf/square-grid`

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/USERNAME/.nvm/versions/node/v8.1.2/bin/node',
1 verbose cli   '/Users/USERNAME/.nvm/versions/node/v8.1.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@turf/square-grid' ]
2 info using npm@5.3.0
3 info using node@v8.1.2
4 verbose npm-session 2082630dca3879dd
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@turf%2fsquare-grid 15520ms (from cache)
8 silly fetchPackageMetaData error for @turf/square-grid@latest Unexpected end of input at 1:16911
8 silly fetchPackageMetaData ctories":{}},"3.10.3":{"name":"@turf/square-grid","version":"3.10.3"
8 silly fetchPackageMetaData                                                                     ^
9 verbose stack SyntaxError: Unexpected end of input at 1:16911
9 verbose stack ctories":{}},"3.10.3":{"name":"@turf/square-grid","version":"3.10.3"
9 verbose stack                                                                     ^
9 verbose stack     at Object.parseJSON (/Users/USERNAME/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
9 verbose stack     at parse (/Users/USERNAME/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
9 verbose stack     at consumeBody.call.then.buffer (/Users/USERNAME/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
9 verbose stack     at <anonymous>
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:169:7)
10 verbose cwd /Users/USERNAME/Desktop/test
11 verbose Darwin 16.7.0
12 verbose argv "/Users/USERNAME/.nvm/versions/node/v8.1.2/bin/node" "/Users/USERNAME/.nvm/versions/node/v8.1.2/bin/npm" "install" "--save" "@turf/square-grid"
13 verbose node v8.1.2
14 verbose npm  v5.3.0
15 error Unexpected end of input at 1:16911
15 error ctories":{}},"3.10.3":{"name":"@turf/square-grid","version":"3.10.3"
15 error                                                                     ^
16 verbose exit [ 1, true ]
```

Any idea?

**Comment by rowanwins** [comment]
Gday @rsancheza09 

I just tried to install it and didn't run into any issues
````
npm install @turf/square-grid
````
My only other idea would be to perhaps also double check your package.json file to check that it's valid json?

Hope that helps

**Comment by rsancheza09** [comment]
Thank you... Apparently it was an issue with nvm.
I removed nvm then I installed node from the site.

Thanks and regards
